Modified assemble/run scripts

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -1,27 +1,99 @@
 #!/bin/bash -e
 #
-# S2I assemble script for the 's2i-jhipster' image.
-# The 'assemble' script builds your application source so that it is ready to run.
+# S2I assemble script for the 'jhipster-s2i' image.
+# The 'assemble' script builds your application source ready to run.
 #
 # For more information refer to the documentation:
 #	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
 #
 
-if [[ "$1" == "-h" ]]; then
-	# If the 's2i-jhipster' assemble script is executed with '-h' flag,
+if [ "$1" = "-h" ]; then
+	# If the 'jhipster-s2i' assemble script is executed with '-h' flag,
 	# print the usage.
-	exec /usr/libexec/s2i/usage
+	exec /usr/local/s2i/usage
 fi
 
-# Restore artifacts from the previous build (if they exist).
-#
-if [ "$(ls /tmp/artifacts/ 2>/dev/null)" ]; then
-  echo "---> Restoring build artifacts..."
-  mv /tmp/artifacts/. ./
+# # Restore artifacts from the previous build (if they exist).
+# #
+# if [ "$(ls /tmp/artifacts/ 2>/dev/null)" ]; then
+#   echo "---> Restoring build artifacts"
+#   mv /tmp/artifacts/. ./
+# fi
+# 
+# echo "---> Installing application source"
+# cp -Rf /tmp/src/. ./
+# 
+# echo "---> Building application from source"
+# # TODO: Add build steps for your application, eg npm install, bundle install
+
+##############################################################################
+
+# Source code provided to STI is at ${HOME}/source
+HOME=/opt/app-root/src
+LOCAL_SOURCE_DIR=${HOME}/source
+mkdir -p $LOCAL_SOURCE_DIR
+
+DEPLOY_DIR=/opt/openshift
+
+# the subdirectory within LOCAL_SOURCE_DIR from where we should copy build artifacts
+ARTIFACT_DIR=${ARTIFACT_DIR-target}
+
+function copy_artifacts() {
+  if [ -d $LOCAL_SOURCE_DIR/$1 ]; then
+    echo "Copying all WAR artifacts from $LOCAL_SOURCE_DIR/$1 directory into $DEPLOY_DIR for later deployment..."
+    cp -v $LOCAL_SOURCE_DIR/$1/*.war $DEPLOY_DIR
+  fi
+}
+
+# Copy the source for compilation
+cp -ad /tmp/src/* $LOCAL_SOURCE_DIR
+
+# If a pom.xml is present, this is a normal build scenario
+# so run maven.
+if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
+  echo "Building with maven. $LOCAL_SOURCE_DIR/pom.xml found."
+  pushd $LOCAL_SOURCE_DIR &> /dev/null
+
+  if [ -z "$BUILDER_ARGS" ]; then
+    export BUILDER_ARGS="clean package -Pdev -DskipTests"
+  fi
+
+  echo "Found pom.xml... attempting to build with 'mvn -e ${BUILDER_ARGS}'"
+
+  echo "Maven version:"
+  mvn --version
+
+  # Execute Build
+  ./mvnw $BUILDER_ARGS
+
+  ERR=$?
+  if [ $ERR -ne 0 ]; then
+    echo "Aborting due to error code $ERR from Maven build"
+    exit $ERR
+  fi
+
+  # Copy built artifacts (if any!) from the target/ directory
+  # to the $DEPLOY_DIR directory for later deployment
+  copy_artifacts target
+
+  # clean up after maven
+  mvn clean
+  if [ -d "$HOME/.m2/repository" ]; then
+    rm -rf "$HOME/.m2/repository"
+  fi
+  if [ -d "$HOME/.npm" ]; then
+    rm -rf "$HOME/.npm"
+  fi
+
+
+  popd &> /dev/null
 fi
 
-echo "---> Installing application source..."
-cp -Rf /tmp/src/. ./
-
-echo "---> Building application from source..."
-# TODO: Add build steps for your application, eg npm install, bundle install
+# As jhipster you should only have 1 fat war
+if [ $(ls /opt/openshift/*.war | wc -l) -eq 1 ]; then
+  mv /opt/openshift/*.war /opt/openshift/app.war
+  [ ! -f /opt/openshift/app.war ] && echo "Application could not be properly built." && exit 1 
+  echo "Application war file is located in /opt/openshift/app.war"
+else
+  exit 1
+fi
